# General
serverName: UUID # Each server within a cluster needs a unique name. Set to UUID to have deepstream autogenerate a unique id
showLogo: true # Show the deepstream logo on startup (highly recommended)
logLevel: INFO # Log messages with this level and above. Valid levels are DEBUG, INFO, WARN, ERROR, OFF
#libDir: ../lib  # Directory where all plugins reside

# Connectivity
webServerEnabled: true # accept incoming HTTP long-polling and websocket connections
tcpServerEnabled: true # accept incoming TCP connections
port: 6020 # port for the HTTP/websocket server
host: 0.0.0.0 # host for the HTTP/websocket server
tcpPort: 6021 # port for the TCP server
tcpHost: 0.0.0.0 # host for the TCP server

#Authentication
auth:
# reading users and passwords from a file
  type: file
  options:
    path: ./users.yml # Path to the user file. Can be json, js or yml
    hash: 'md5' # the name of a HMAC digest algorithm
    iterations: 100 # the number of times the algorithm should be applied
    keyLength: 32 # the length of the resulting key

# Permissioning
permission:
  type: config # Only config or custom permissionHandler at the moment
  options:
    path: ./permissions.yml # Path to the permissionFile. Can be json, js or yml
    maxRuleIterations: 3 # Amount of times nested cross-references will be loaded. Avoids endless loops
    cacheEvacuationInterval: 60000 # PermissionResults are cached to increase performance. Lower number means more loading